[theme]
primaryColor="#F0F2F6" # Couleur des accents, contour barre de messages
backgroundColor="#3bb1fa" #Gros fond bleu
secondaryBackgroundColor="#F0F2F6" # Couleur barre des messages
textColor="#31333F"
font="monospace"